server:
  port: 8081
spring:
  redis:
    datasource: 0
    port: 6379
    host: 172.26.165.200
    lettuce:
      pool:
        min-idle: 5
        max-idle: 10
        max-active: 8
        max-wait: 1
      shutdown-timeout: 100